### ISSUE TITLE
Delete CNAME from gh-pages branch

### ISSUE THREAD

**Issue by iabhi7** [theabhitech/iabhi#1]
Hey @errorLAD can you please delete the CNAME from the gh-pages branch as well.

**Comment by errorLAD** [comment]
Done

Sent from Yahoo Mail on Android 
 
  On Mon, Jun 8, 2020 at 15:41, vibrantabhi19<notifications@github.com> wrote:   


Hey @errorLAD can you please delete the CNAME from the gh-pages branch as well.

**Comment by iabhi7** [comment]
Thanks
